// src/lib/components/CoverageStats.svelte
<script lang="ts">
	import { get } from 'svelte/store';
	import type { FilteredMatch } from '$lib/types';
	import { coveragePlan } from '$lib/stores/coveragePlan';
	import { coverageStatus } from '$lib/stores/coverageStatus';
	import { getTeamIdentifier } from '$lib/stores/filters';
	import { calculateTeamCoverageMetrics, calculateCoverageDashboardMetrics } from '$lib/utils/coverageStats';
	import { exportCoverageStatsToCSV, exportCoverageStatsToJSON } from '$lib/utils/coverageStats';
	import type { TeamCoverageMetrics, CoverageDashboardMetrics } from '$lib/utils/coverageStats';
	
	export let matches: FilteredMatch[];
	
	const currentPlan = get(coveragePlan);
	const selectedMatchIds = currentPlan;
	
	// Build coverage status map
	$: coverageStatusMap = (() => {
		const map = new Map<string, string>();
		matches.forEach(match => {
			const teamId = getTeamIdentifier(match);
			if (teamId) {
				map.set(teamId, coverageStatus.getTeamStatus(teamId));
			}
		});
		return map;
	})();
	
	// Calculate metrics
	$: teamMetrics = (() => {
		return calculateTeamCoverageMetrics(
			matches,
			selectedMatchIds,
			coverageStatusMap as any,
			getTeamIdentifier
		);
	})();
	
	$: dashboardMetrics = (() => {
		return calculateCoverageDashboardMetrics(
			matches,
			selectedMatchIds,
			coverageStatusMap as any,
			getTeamIdentifier
		);
	})();
	
	function handleExportCSV() {
		const csv = exportCoverageStatsToCSV(teamMetrics, dashboardMetrics);
		const blob = new Blob([csv], { type: 'text/csv' });
		const url = URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `coverage-stats-${new Date().toISOString().split('T')[0]}.csv`;
		link.click();
		URL.revokeObjectURL(url);
	}
	
	function handleExportJSON() {
		const json = exportCoverageStatsToJSON(teamMetrics, dashboardMetrics);
		const blob = new Blob([json], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `coverage-stats-${new Date().toISOString().split('T')[0]}.json`;
		link.click();
		URL.revokeObjectURL(url);
	}
</script>

<div class="space-y-6">
	<!-- Dashboard Summary -->
	<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
		<!-- Coverage Percentage -->
		<div class="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
			<div class="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Coverage</div>
			<div class="text-2xl font-bold text-[#f8f8f9] mb-1">
				{dashboardMetrics.coveragePercentage.toFixed(1)}%
			</div>
			<div class="text-xs text-[#9fa2ab]">
				{dashboardMetrics.coveredTeams + dashboardMetrics.partiallyCoveredTeams} of {dashboardMetrics.totalTeams} teams
			</div>
		</div>

		<!-- Covered Teams -->
		<div class="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
			<div class="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Covered</div>
			<div class="text-2xl font-bold text-green-400 mb-1">
				{dashboardMetrics.coveredTeams}
			</div>
			<div class="text-xs text-[#9fa2ab]">
				{dashboardMetrics.partiallyCoveredTeams} partially covered
			</div>
		</div>

		<!-- Planned Teams -->
		<div class="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
			<div class="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Planned</div>
			<div class="text-2xl font-bold text-[#eab308] mb-1">
				{dashboardMetrics.plannedTeams}
			</div>
			<div class="text-xs text-[#9fa2ab]">
				{dashboardMetrics.plannedPercentage.toFixed(1)}% of teams
			</div>
		</div>

		<!-- Uncovered Teams -->
		<div class="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
			<div class="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Uncovered</div>
			<div class="text-2xl font-bold text-[#808593] mb-1">
				{dashboardMetrics.uncoveredTeams}
			</div>
			<div class="text-xs text-[#9fa2ab]">
				{dashboardMetrics.totalTeams > 0 ? ((dashboardMetrics.uncoveredTeams / dashboardMetrics.totalTeams) * 100).toFixed(1) : 0}% remaining
			</div>
		</div>
	</div>

	<!-- Coverage Progress Bar -->
	<div class="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
		<div class="flex items-center justify-between mb-2">
			<div class="text-sm font-medium text-[#f8f8f9]">Overall Coverage Progress</div>
			<div class="text-xs text-[#9fa2ab]">{dashboardMetrics.coveragePercentage.toFixed(1)}%</div>
		</div>
		<div class="w-full h-3 bg-[#454654] rounded-full overflow-hidden">
			<div
				class="h-full bg-[#eab308] transition-all duration-300"
				style="width: {Math.min(dashboardMetrics.coveragePercentage, 100)}%;"
			/>
		</div>
	</div>

	<!-- Team Breakdown -->
	<div class="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
		<div class="flex items-center justify-between mb-4">
			<div class="text-sm font-medium text-[#f8f8f9]">Team Coverage Breakdown</div>
			<div class="flex gap-2">
				<button
					onclick={handleExportCSV}
					class="px-3 py-1.5 text-xs font-medium rounded bg-[#454654] text-[#c0c2c8] hover:text-[#f8f8f9] hover:bg-[#525463] border border-[#525463] transition-colors"
				>
					Export CSV
				</button>
				<button
					onclick={handleExportJSON}
					class="px-3 py-1.5 text-xs font-medium rounded bg-[#454654] text-[#c0c2c8] hover:text-[#f8f8f9] hover:bg-[#525463] border border-[#525463] transition-colors"
				>
					Export JSON
				</button>
			</div>
		</div>
		
		<div class="space-y-3 max-h-[400px] overflow-y-auto">
			{#each teamMetrics as team}
				<div class="flex items-center justify-between">
					<div class="flex items-center gap-3 flex-1 min-w-0">
						<div class="flex items-center gap-2 flex-shrink-0">
							<div class="w-3 h-3 rounded {team.status === 'covered' ? 'bg-green-500' : team.status === 'partially-covered' ? 'bg-[#f59e0b]' : team.status === 'planned' ? 'bg-[#eab308]' : 'bg-[#808593]'}" />
							<div class="text-sm font-medium text-[#f8f8f9]">
								Team {team.teamId}
							</div>
						</div>
						<div class="text-xs text-[#9fa2ab]">
							{team.coveredMatches}/{team.totalMatches} matches
							{#if team.plannedMatches > 0}
								• {team.plannedMatches} planned
							{/if}
						</div>
					</div>
					<div class="flex items-center gap-2 flex-shrink-0">
						<div class="w-24 h-2 bg-[#454654] rounded-full overflow-hidden">
							<div
								class="h-full transition-all duration-300 {team.status === 'covered' ? 'bg-green-500' : team.status === 'partially-covered' ? 'bg-[#f59e0b]' : team.status === 'planned' ? 'bg-[#eab308]' : 'bg-[#808593]'}"
								style="width: {Math.min(team.coveragePercentage, 100)}%;"
							/>
						</div>
						<div class="text-xs text-[#9fa2ab] w-12 text-right">
							{team.coveragePercentage.toFixed(0)}%
						</div>
					</div>
				</div>
			{/each}
		</div>
	</div>
</div>

// src/components/CoverageStats.tsx
import { useMemo } from 'react';
import type { FilteredMatch } from '../types';
import type { useCoveragePlan } from '../hooks/useCoveragePlan';
import { useCoverageStatus } from '../hooks/useCoverageStatus';
import { useFilters } from '../hooks/useFilters';
import { calculateTeamCoverageMetrics, calculateCoverageDashboardMetrics } from '../utils/coverageStats';
import { exportCoverageStatsToCSV, exportCoverageStatsToJSON } from '../utils/coverageStats';
import type { TeamCoverageMetrics, CoverageDashboardMetrics } from '../utils/coverageStats';

interface CoverageStatsProps {
  matches: FilteredMatch[];
  coveragePlan: ReturnType<typeof useCoveragePlan>;
}

export const CoverageStats = ({ matches, coveragePlan }: CoverageStatsProps) => {
  const coverageStatus = useCoverageStatus();
  const { getTeamIdentifier } = useFilters();

  // Build coverage status map
  const coverageStatusMap = useMemo(() => {
    const map = new Map<string, string>();
    matches.forEach(match => {
      const teamId = getTeamIdentifier(match);
      if (teamId) {
        map.set(teamId, coverageStatus.getTeamStatus(teamId));
      }
    });
    return map;
  }, [matches, coverageStatus, getTeamIdentifier]);

  // Calculate metrics
  const selectedMatchIds = useMemo(() => {
    return new Set(coveragePlan.selectedMatches);
  }, [coveragePlan.selectedMatches]);

  const teamMetrics = useMemo<TeamCoverageMetrics[]>(() => {
    return calculateTeamCoverageMetrics(
      matches,
      selectedMatchIds,
      coverageStatusMap as any,
      getTeamIdentifier
    );
  }, [matches, selectedMatchIds, coverageStatusMap, getTeamIdentifier]);

  const dashboardMetrics = useMemo<CoverageDashboardMetrics>(() => {
    return calculateCoverageDashboardMetrics(
      matches,
      selectedMatchIds,
      coverageStatusMap as any,
      getTeamIdentifier
    );
  }, [matches, selectedMatchIds, coverageStatusMap, getTeamIdentifier]);

  const handleExportCSV = () => {
    const csv = exportCoverageStatsToCSV(teamMetrics, dashboardMetrics);
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `coverage-stats-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    const json = exportCoverageStatsToJSON(teamMetrics, dashboardMetrics);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `coverage-stats-${new Date().toISOString().split('T')[0]}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Dashboard Summary */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Coverage Percentage */}
        <div className="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
          <div className="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Coverage</div>
          <div className="text-2xl font-bold text-[#f8f8f9] mb-1">
            {dashboardMetrics.coveragePercentage.toFixed(1)}%
          </div>
          <div className="text-xs text-[#9fa2ab]">
            {dashboardMetrics.coveredTeams + dashboardMetrics.partiallyCoveredTeams} of {dashboardMetrics.totalTeams} teams
          </div>
        </div>

        {/* Covered Teams */}
        <div className="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
          <div className="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Covered</div>
          <div className="text-2xl font-bold text-green-400 mb-1">
            {dashboardMetrics.coveredTeams}
          </div>
          <div className="text-xs text-[#9fa2ab]">
            {dashboardMetrics.partiallyCoveredTeams} partially covered
          </div>
        </div>

        {/* Planned Teams */}
        <div className="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
          <div className="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Planned</div>
          <div className="text-2xl font-bold text-[#eab308] mb-1">
            {dashboardMetrics.plannedTeams}
          </div>
          <div className="text-xs text-[#9fa2ab]">
            {dashboardMetrics.plannedPercentage.toFixed(1)}% of teams
          </div>
        </div>

        {/* Uncovered Teams */}
        <div className="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
          <div className="text-xs text-[#9fa2ab] uppercase tracking-wider mb-1">Uncovered</div>
          <div className="text-2xl font-bold text-[#808593] mb-1">
            {dashboardMetrics.uncoveredTeams}
          </div>
          <div className="text-xs text-[#9fa2ab]">
            {dashboardMetrics.totalTeams > 0 ? ((dashboardMetrics.uncoveredTeams / dashboardMetrics.totalTeams) * 100).toFixed(1) : 0}% remaining
          </div>
        </div>
      </div>

      {/* Coverage Progress Bar */}
      <div className="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
        <div className="flex items-center justify-between mb-2">
          <div className="text-sm font-medium text-[#f8f8f9]">Overall Coverage Progress</div>
          <div className="text-xs text-[#9fa2ab]">{dashboardMetrics.coveragePercentage.toFixed(1)}%</div>
        </div>
        <div className="w-full h-3 bg-[#454654] rounded-full overflow-hidden">
          <div
            className="h-full bg-[#eab308] transition-all duration-300"
            style={{ width: `${Math.min(dashboardMetrics.coveragePercentage, 100)}%` }}
          />
        </div>
      </div>

      {/* Team Breakdown */}
      <div className="rounded-lg border border-[#454654] bg-[#3b3c48] p-4">
        <div className="flex items-center justify-between mb-4">
          <div className="text-sm font-medium text-[#f8f8f9]">Team Coverage Breakdown</div>
          <div className="flex gap-2">
            <button
              onClick={handleExportCSV}
              className="px-3 py-1.5 text-xs font-medium rounded bg-[#454654] text-[#c0c2c8] hover:text-[#f8f8f9] hover:bg-[#525463] border border-[#525463] transition-colors"
            >
              Export CSV
            </button>
            <button
              onClick={handleExportJSON}
              className="px-3 py-1.5 text-xs font-medium rounded bg-[#454654] text-[#c0c2c8] hover:text-[#f8f8f9] hover:bg-[#525463] border border-[#525463] transition-colors"
            >
              Export JSON
            </button>
          </div>
        </div>
        
        <div className="space-y-3 max-h-[400px] overflow-y-auto">
          {teamMetrics.map((team) => (
            <div key={team.teamId} className="flex items-center justify-between">
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-shrink-0">
                  <div className={`w-3 h-3 rounded ${
                    team.status === 'covered'
                      ? 'bg-green-500'
                      : team.status === 'partially-covered'
                      ? 'bg-[#f59e0b]'
                      : team.status === 'planned'
                      ? 'bg-[#eab308]'
                      : 'bg-[#808593]'
                  }`} />
                  <div className="text-sm font-medium text-[#f8f8f9]">
                    Team {team.teamId}
                  </div>
                </div>
                <div className="text-xs text-[#9fa2ab]">
                  {team.coveredMatches}/{team.totalMatches} matches
                  {team.plannedMatches > 0 && ` • ${team.plannedMatches} planned`}
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <div className="w-24 h-2 bg-[#454654] rounded-full overflow-hidden">
                  <div
                    className={`h-full transition-all duration-300 ${
                      team.status === 'covered'
                        ? 'bg-green-500'
                        : team.status === 'partially-covered'
                        ? 'bg-[#f59e0b]'
                        : team.status === 'planned'
                        ? 'bg-[#eab308]'
                        : 'bg-[#808593]'
                    }`}
                    style={{ width: `${Math.min(team.coveragePercentage, 100)}%` }}
                  />
                </div>
                <div className="text-xs text-[#9fa2ab] w-12 text-right">
                  {team.coveragePercentage.toFixed(0)}%
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
